# Generated by Django 6.1.1 on 2026-10-03 14:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('insurance', 'Tata AIA Life Insurance'), ('nutrition', 'Herbalife Nutrition'), ('kangen', 'Kangen Water'), ('solar', 'Solar Panel Installation'), ('general', 'General Enterprise')], max_length=30)),
                ('category', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True)),
                ('author_name', models.CharField(default='VentureQuad Editorial', max_length=100)),
                ('read_time', models.CharField(default='4 min read', max_length=30)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('insurance', 'Tata AIA Life Insurance'), ('nutrition', 'Herbalife Nutrition'), ('kangen', 'Kangen Water'), ('solar', 'Solar Panel Installation'), ('general', 'General Enterprise')], max_length=30)),
                ('calculator_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('input_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('insurance_admin', 'Tata AIA Insurance Admin'), ('nutrition_admin', 'Herbalife Nutrition Admin'), ('kangen_admin', 'Kangen Water Admin'), ('solar_admin', 'Solar Energy Admin'), ('customer', 'Customer')], default='customer', max_length=30)),
                ('business_division', models.CharField(blank=True, choices=[('insurance', 'Tata AIA Life Insurance'), ('nutrition', 'Herbalife Nutrition'), ('kangen', 'Kangen Water'), ('solar', 'Solar Panel Installation'), ('general', 'General Enterprise')], default='general', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('insurance', 'Tata AIA Life Insurance'), ('nutrition', 'Herbalife Nutrition'), ('kangen', 'Kangen Water'), ('solar', 'Solar Panel Installation'), ('general', 'General Enterprise')], max_length=30)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=25)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('service_type', models.CharField(help_text='e.g. Tata AIA HLV Consultation, Herbalife Wellness Evaluation, Kangen Live Demo, Solar Rooftop Site Survey', max_length=200)),
                ('mode', models.CharField(choices=[('in_person', 'In-Person / Home Visit'), ('online', 'Video Conference'), ('phone', 'Phone Consultation')], default='in_person', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=30)),
                ('location_or_link', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('insurance', 'Tata AIA Life Insurance'), ('nutrition', 'Herbalife Nutrition'), ('kangen', 'Kangen Water'), ('solar', 'Solar Panel Installation'), ('general', 'General Enterprise')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('policy_or_system_details', models.TextField(blank=True, help_text='e.g. Policy #, Machine Serial #, Solar 5kW rooftop', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('insurance', 'Tata AIA Life Insurance'), ('nutrition', 'Herbalife Nutrition'), ('kangen', 'Kangen Water'), ('solar', 'Solar Panel Installation'), ('general', 'General Enterprise')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=25)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('service_interest', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal / Demo Sent'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], default='new', max_length=30)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('calculator_data', models.JSONField(blank=True, help_text='Saved calculations associated with this lead', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('insurance', 'Tata AIA Life Insurance'), ('nutrition', 'Herbalife Nutrition'), ('kangen', 'Kangen Water'), ('solar', 'Solar Panel Installation'), ('general', 'General Enterprise')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='api.appointment')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='api.lead')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
