# Generated by Django 6.1.1 on 2026-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal / Demo Sent'), ('converted', 'Converted'), ('won', 'Closed Won'), ('closed', 'Closed'), ('lost', 'Closed Lost')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('insurance_admin', 'Tata AIA Insurance Admin'), ('insurance_agent', 'Tata AIA Insurance Agent'), ('nutrition_admin', 'Herbalife Nutrition Admin'), ('nutrition_rep', 'Herbalife Representative'), ('kangen_admin', 'Kangen Water Admin'), ('kangen_rep', 'Kangen Water Representative'), ('solar_admin', 'Solar Energy Admin'), ('solar_sales', 'Solar Sales Agent'), ('solar_installer', 'Solar Installation Team'), ('customer', 'Customer')], default='customer', max_length=30),
        ),
    ]
