import React, { useState } from 'react';
import { DivisionNav } from '../../components/common/DivisionNav';
import { SunMedium, ChevronDown, HelpCircle, ArrowRight } from 'lucide-react';
import { useAppointmentModal } from '../../context/AppointmentModalContext';

export const SolarFAQ: React.FC = () => {
  const { openBookingModal } = useAppointmentModal();
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      q: 'How does the PM Surya Ghar: Muft Bijli Yojana Central Subsidy work in 2024–2026?',
      a: 'Under the PM Surya Ghar national scheme launched by the Prime Minister, residential homeowners receive direct DBT (Direct Benefit Transfer) bank subsidies: ₹30,000 for a 1 kW system; ₹60,000 for a 2 kW system; and a flat maximum subsidy of ₹78,000 for systems of 3 kW or greater capacity. As an empaneled national vendor, our team handles the entire National Portal registration, DISCOM approvals, and subsidy credit processing directly into your bank account.'
    },
    {
      q: 'How does On-Grid Net Metering work with my electricity board (DISCOM)?',
      a: 'On-grid solar works synchronously with your DISCOM grid (e.g. TSSPDCL, APEPDCL, MSEDCL, BESCOM). A bidirectional net meter replaces your traditional meter. During sunny hours, excess units generated by your rooftop panels are exported to the grid, spinning your meter backwards. At the end of the monthly billing cycle, you only pay for net imported units (Import minus Export). If you export more than you consume, credits roll over to subsequent months.'
    },
    {
      q: 'What is the payback period for a residential rooftop solar system?',
      a: 'For a typical 3 kW to 5 kW residential system with an average monthly electricity bill of ₹4,500 – ₹9,000, the post-subsidy investment is recovered in just 3.2 to 4.2 years. After this payback break-even point, your electricity is virtually 100% free for the remaining 20+ years of the panel’s operating life, yielding a 25% to 32% tax-free annual ROI.'
    },
    {
      q: 'What happens during cloudy or rainy monsoon days?',
      a: 'Solar photovoltaic panels generate electricity from ambient daylight (diffuse photon radiation), not direct heat. While production drops to approximately 25% to 45% of peak capacity during heavily overcast days, your home automatically draws seamless supplementary electricity from the DISCOM grid without any interruption or flicker.'
    },
    {
      q: 'What warranties and maintenance are provided with our solar installations?',
      a: 'Every installation features: 1) 25-Year Linear Power Output Warranty on Tier-1 ALMM & DCR Mono PERC panels (guaranteeing ≥80% output at Year 25); 2) 8 to 10-Year Comprehensive Inverter Replacement Warranty; 3) 5-Year Workmanship & Structure Warranty engineered to withstand 160 km/h wind gusts; and 4) Free periodic cleaning and performance monitoring visits during Year 1.'
    },
    {
      q: 'Can solar panels be installed on roofs with water tanks or limited space?',
      a: 'Yes. We specialize in custom high-rise elevated galvanized super-structures (GI or aluminum). These structures raise the panels 7 to 10 feet above your terrace floor, allowing you to retain 100% of your usable terrace space for evening walking, clothes drying, or rooftop gardens while simultaneously keeping the top floor 3°C to 5°C cooler during summer.'
    }
  ];

  return (
    <div>
      <DivisionNav division="solar" />

      <div className="bg-slate-50 text-slate-800 min-h-screen py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
          
          {/* Header */}
          <div className="text-center space-y-3">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-amber-50 border border-amber-200 text-amber-800 text-xs font-bold">
              <SunMedium className="w-4 h-4 text-amber-600" />
              <span>Renewable Clean Energy Portal</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
              Rooftop Solar & Subsidy FAQs
            </h1>
            <p className="text-slate-600 text-sm max-w-xl mx-auto">
              Everything you need to know about the PM Surya Ghar ₹78,000 direct subsidy, net metering, ROI payback, panel warranties, and elevated structures.
            </p>
          </div>

          {/* Accordion List */}
          <div className="space-y-3">
            {faqs.map((faq, idx) => {
              const isOpen = openIndex === idx;
              return (
                <div
                  key={idx}
                  className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden transition"
                >
                  <button
                    onClick={() => setOpenIndex(isOpen ? null : idx)}
                    className="w-full p-5 text-left flex items-center justify-between gap-4 hover:bg-slate-50 transition"
                  >
                    <span className="font-bold text-sm sm:text-base text-slate-900 flex items-center gap-3">
                      <HelpCircle className="w-4 h-4 text-amber-600 shrink-0" />
                      <span>{faq.q}</span>
                    </span>
                    <ChevronDown className={`w-4 h-4 text-slate-400 shrink-0 transition-transform ${isOpen ? 'rotate-180 text-amber-600' : ''}`} />
                  </button>
                  {isOpen && (
                    <div className="p-5 pt-0 text-xs sm:text-sm text-slate-600 leading-relaxed border-t border-slate-100 bg-slate-50/50">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Consultation CTA Card */}
          <div className="bg-white border border-amber-200 rounded-2xl p-8 text-center space-y-3 shadow-sm">
            <h3 className="text-xl font-bold text-slate-900">Get a Free Rooftop Feasibility & Shadow Study</h3>
            <p className="text-xs sm:text-sm text-slate-600 max-w-md mx-auto">
              Our certified solar EPC engineers conduct a physical or drone terrace survey to assess your exact solar generation and subsidy benefit.
            </p>
            <div className="flex flex-wrap justify-center gap-3 pt-2">
              <button
                onClick={() => openBookingModal({ division: 'solar', service: 'Free Rooftop Engineering Feasibility & Shadow Audit' })}
                className="px-6 py-3 rounded-xl bg-amber-600 hover:bg-amber-700 text-white font-bold text-xs shadow-sm transition flex items-center gap-2 cursor-pointer"
              >
                <span>Book Free Rooftop Site Survey</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};
